2_1_type_safety
PickDough/rust-incubator pull request #13
Opened 2024-03-11 11:28 UTC by PickDough

Resolves [Step ]()

## Task

## Solution

2024-03-13 14:13 UTC, evdokimovs requested changes
1. Добавьте возможность получать `post::Body`, `post::Title` с помощью методов из любого стейта поста
2. Добавьте структуру `PostStore`, которая будет хранить все возможные посты в независимости от конкретного стейта
3. И реализуйте методы, которые позволят работать с этим `PostStore` удобным образом. Вот примерный кейс использования `PostStore`, который хочется получить на выходе:

```rust
fn main() {
    let mut store = PostStore::new();
    let post: Post<New> = Post::new(todo!());
    let post_id = post.id();
    store.add_post(post_id, post);

    // Should work for Posts in any state without providing concrete state of Post.
    // So in this closure we should receive heterogeneous Post.
    let (title, body) = store.map_post_by_id(post_id, |post| {
        (post.title(), post.body())
    }).unwrap();
    println!("{title}\n\n{body}");

    // Unwrap should panic if state is not New or there are no Post with this ID
    let post: Post<New> = store.take(post_id).unwrap();
    let post: Post<UnModerated> = post.publish();
    // Should accept any Post<T> here
    store.add_post(post_id, post);
}
```

Какие-то моменты можете поменять (например `post::Id` можно доставать из `Post` в `PostStore`), но основная суть работы со стейтами должна остаться.

2024-03-13 14:13 UTC, evdokimovs commented on 2_idioms/2_1_type_safety/src/main.rs
> +        Post { id: post::Id(0), user_id, title, body, state: Default::default() }
`post::Id(0)` выглядит некорректным. У Вас так все посты будут с одним и тем же `post::Id`. Поправьте, пожалуйста.

2024-03-14 10:11 UTC, PickDough commented on 2_idioms/2_1_type_safety/src/main.rs
> +        Post { id: post::Id(0), user_id, title, body, state: Default::default() }
А кто должен генерировать уникальные айди в таком случае? Без доступа к базе, невозможно сделать уникальный ключ, не используя UUID, поэтому я оставлял ноль как пометку, что пост новый.

2024-03-15 14:46 UTC, PickDough commented
Сделал все `TryFrom`, `Into` вручную, хотя видел крейт `enum_dispatch`, но так мне самому более понятно стало.

2024-03-19 15:24 UTC, evdokimovs approved these changes

2024-03-20 10:29 UTC, merged