2_5_exhaustivity
PickDough/rust-incubator pull request #17
Opened 2024-03-12 10:58 UTC by PickDough

Resolves [Step ]()

## Task

## Solution

2024-03-15 09:19 UTC, evdokimovs requested changes
1. Почему только обработка ивента `UserCreated` у Вас exhaustive? Остальные ивенты тоже нужно раскрывать также как `UserCreated`.
2. Есть смысл использовать `#[non_exhastive]` для типов, которые в будущем могут быть расширены

2024-03-15 09:57 UTC, PickDough commented
> 1. Почему только обработка ивента `UserCreated` у Вас exhaustive? Остальные ивенты тоже нужно раскрывать также как `UserCreated`.
> 
>     2. Есть смысл использовать `#[non_exhastive]` для типов, которые в будущем могут быть расширены

Мне кажется, что когда нам нужно только одно поле с ивента, то нет надобности в раскрытии структуры полностью

2024-03-15 10:48 UTC, evdokimovs commented
@PickDough ,

> Мне кажется, что когда нам нужно только одно поле с ивента, то нет надобности в раскрытии структуры полностью

Суть в том, что в будущем могут появиться какие-то новые поля в ивенте, которые Вы не хотите потерять. Вы же не можете предсказать как изменится бизнес логика в будущем и добавится ли там что-то новое, именно для этого и существует exhaustivity (даже если на данный момент там всего одно поле).

2024-03-19 15:24 UTC, evdokimovs approved these changes

2024-03-20 10:29 UTC, merged