1 1 default clone copy
PickDough/rust-incubator pull request #2
Opened 2024-03-04 11:02 UTC by PickDough

Resolves [Step ]()

## Task

## Solution

2024-03-04 13:21 UTC, evdokimovs requested changes

2024-03-04 13:21 UTC, evdokimovs commented on 1_concepts/1_1_default_clone_copy/src/main.rs
> +        assert!(points.len() > 0, "Polyline type represents a non-empty set of Point");
Сделайте так, чтобы это была не рантайм проверка. Сделать compile-time гарантию, что `Polyline` будет не нулевого размера можно с помощью системы типов.

2024-03-05 10:02 UTC, PickDough commented on 1_concepts/1_1_default_clone_copy/src/main.rs
> +        assert!(points.len() > 0, "Polyline type represents a non-empty set of Point");
Ready for review

2024-03-06 08:26 UTC, evdokimovs commented on 1_concepts/1_1_default_clone_copy/src/main.rs
> +        assert!(points.len() > 0, "Polyline type represents a non-empty set of Point");
@PickDough ,

> Ready for review

You can use "Re-request review" button for this.

2024-03-06 08:26 UTC, evdokimovs approved these changes

2024-03-06 13:32 UTC, merged