3_8_log
PickDough/rust-incubator pull request #28
Opened 2024-03-21 13:41 UTC by PickDough

Resolves [Step ]()

## Task

## Solution

2024-03-27 11:41 UTC, evdokimovs requested changes
Access логи должны быть локальными. То есть в файлик `access.log` должны идти только логи, которые мы явно пропишем.

К примеру, у нас есть модуль HTTP сервера, и внутри него мы хотим логировать все запросы к серверу. Соответственно там мы хотим делать что-то типа такого:

```rust
log::error!(access_log, "Accesses /ws endpoint");
```

2024-03-27 12:07 UTC, PickDough commented
> Access логи должны быть локальными. То есть в файлик `access.log` должны идти только логи, которые мы явно пропишем.
> 
> К примеру, у нас есть модуль HTTP сервера, и внутри него мы хотим логировать все запросы к серверу. Соответственно там мы хотим делать что-то типа такого:
> 
> ```rust
> log::error!(access_log, "Accesses /ws endpoint");
> ```

 Понял идею и даже запушил изминения, но такая настройка обычно делается вручную, с конфига или RUST_LOG?

2024-03-27 13:12 UTC, evdokimovs commented
@PickDough ,

> Понял идею и даже запушил изминения, но такая настройка обычно делается вручную, с конфига или RUST_LOG?

Если Вы про прокидывание каких-то фильтров логов по крейтам, то обычно это делается через env var'ы, но это требует реализации на стороне приложения, и тут это не требуется.

В рамках того о чем я говорю, то идея иметь как бы два варианта логирования. Первый логгер должен будет использоваться для всех `log::*!(), а второй должен быть локальным и может, допустим, храниться в структуре HTTP сервера, и при обработке каких-то запросов он, например, будет писать конкретно в него какие-то логи, и эти логи будут идти в файл, а не в stdout/stderr. 

Ближайший пример этого вот такой:

```rust
let local = init_logger_with_file("access.log");
slog::info!(logger, "Hello world!");
```

2024-03-27 13:16 UTC, PickDough commented
@evdokimovs В рамках Вашего примера, функция делает сабскрайбер и возвращает строку, которая будет таргетом, если я правильно его понял?

2024-03-27 15:00 UTC, evdokimovs commented
@PickDough ,

> @evdokimovs В рамках Вашего примера, функция делает сабскрайбер и возвращает строку, которая будет таргетом, если я правильно его понял?


Там очепятка вышла. Выглядеть оно может примерно так:

```rust
let local = init_logger_with_file("access.log");
slog::info!(local, "Hello world!");
```

То есть Вы конкретно можете писать логи в локальный логгер.

2024-03-27 15:09 UTC, PickDough commented
> @PickDough ,
> 
> > @evdokimovs В рамках Вашего примера, функция делает сабскрайбер и возвращает строку, которая будет таргетом, если я правильно его понял?
> 
> Там очепятка вышла. Выглядеть оно может примерно так:
> 
> ```rust
> let local = init_logger_with_file("access.log");
> slog::info!(local, "Hello world!");
> ```
> 
> То есть Вы конкретно можете писать логи в локальный логгер.

В рамках моего кода, я за выбрал `tracing` crate + решил абстрагироватся от его и использувать `log`, сейчас, не залезая в доки, мне известно только target, который является строкой, то есть в этом решение, наверное, передавать логер не получиться архитектурно.

Я понял Вашу идею и подход с помощью объектов. Дайте знать: это решение мне как то изменять, или одно самодостатчно в рамках задания?

2024-03-28 10:35 UTC, evdokimovs commented
@PickDough ,

> В рамках моего кода, я за выбрал `tracing` crate + решил абстрагироватся от его и использувать `log`, сейчас, не залезая в доки, мне известно только target, который является строкой, то есть в этом решение, наверное, передавать логер не получиться архитектурно.
> 
> Я понял Вашу идею и подход с помощью объектов. Дайте знать: это решение мне как то изменять, или одно самодостатчно в рамках задания?

Оставляйте так, поскольку решение на `tracing` в любом случае интереснее выглядит.

2024-03-28 11:57 UTC, merged