1_2_box_pin NOT fully completed
PickDough/rust-incubator pull request #3
Opened 2024-03-04 11:57 UTC by PickDough

Resolves [Step ]()

## Task

## Solution

2024-03-04 13:19 UTC, evdokimovs requested changes

2024-03-04 13:19 UTC, evdokimovs commented on 1_concepts/1_1_default_clone_copy/src/main.rs
Не смешивайте изменения из других веток. Если бренч был создан для Step 1.2, то тут должны быть изменения только касающиеся Step 1.2

То есть, если вкратце, то создавайте новые бренчи всегда от `main`, а не от бренчей предыдущих степов.

Тут и в других уже созданных PR'ах подчистите, пожалуйста, PRы так, чтобы остались только изменения касающиеся соответствующих степов.

2024-03-04 13:22 UTC, PickDough commented on 1_concepts/1_1_default_clone_copy/src/main.rs
Могу ли  сделать мердж на предыдущую ветку, чтобы спрятать эти изменения, или строго с мейном работаем?

2024-03-04 15:20 UTC, evdokimovs commented on 1_concepts/1_1_default_clone_copy/src/main.rs
@PickDough ,

> Могу ли сделать мердж на предыдущую ветку, чтобы спрятать эти изменения, или строго с мейном работаем?

Тогда изменения из `1_2_box_pin` перетекут в `1_1_default_clone_copy`, но при этом в `1_2_box_pin` останутся изменения из `1_1_default_clone_copy`. То есть насколько я понимаю Вашу идею, таким образом Вы сделаете только хуже.

Edited:
Проще через IDE'шку откатить через diff в Вашей ситуации. Через `git reset` у Вас больше проблем будет.

2024-03-06 08:35 UTC, evdokimovs approved these changes

2024-03-06 08:35 UTC, evdokimovs commented on 1_concepts/1_2_box_pin/Cargo.toml
> +tokio ={ version = "1", features = ["full"]}
Fix `Cargo.toml` formatting.

2024-03-06 08:37 UTC, evdokimovs commented
@PickDough ,

> PickDough force-pushed the `1_2_box_pin` branch from `b81f077` to `d397dda` yesterday

На будущее, лучше избегать форс пушей (а лучше вообще никогда их не использовать), поскольку они могут приводить к большому количеству сайд эффектов, в том числе и на чужих ветках.

2024-03-06 13:33 UTC, merged